### ISSUE TITLE
Some crosslinks to non-existing notes

### ISSUE THREAD

**Issue by srfall** [selinaZitrone/notebook_demo#1]
E.g.

https://github.com/selinaZitrone/notebook_demo/blob/7056a852f0a9f3f58aaebcf51d5ac1a80cb9a20f/1_Journal/Weekly/2022-W51.md?plain=1#L34

And the following lines. 

Problem: May lead to confusion for a first time user

Solution: Either create those files, delete these references, or link to a different note ([[Open-Tasks]] seem like it should be [[ALL OPEN TASKS]])

**Comment by AnneLew** [comment]
Thanks! Now there is the correct link.
