### ISSUE TITLE
Add a warning about enabling plugins in the README

### ISSUE THREAD

**Issue by srfall** [selinaZitrone/notebook_demo#2]
As this demo is targeted at first time users you might want to consider adding a note in the README about potential risks when enabling plugins (especially since this vault contains the plugins - So the users are asked if they trust this vault by Obsidian when opening it for the first time.). 

Since plugins have a rather unrestricted access to your computer and can run arbitrary code imo there should be a link to the [documentation](https://help.obsidian.md/Advanced+topics/Community+plugins#Safe+Mode) and maybe some words of caution within the installation instructions.

**Comment by AnneLew** [comment]
Thanks for this feeback! I added a short section with a link to the Readme.
