### ISSUE TITLE
Journal titles

### ISSUE THREAD

**Issue by treeent** [selinaZitrone/notebook_demo#4]
Hi Selina,

I see that your daily and weekly notes do not show the name of their respective files as titles, on top of the page. And that it allows you to put the properties on top and choose a custom title using a level 1 heading. 

How do you do that? Is it a vanilla option of Obsidian? Or thanks to a plugin? Or through a CSS snippet?

Thanks in advance for your help!

**Comment by selinaZitrone** [comment]
Hi @treeent, 

This is a basic option that you can access from the Obsidian settings. You have to go to Settings -> Appearance -> Interface and there you can turn "Show inline title" on or off. In the demo-vault, we turned it off as a default, that's why you don't see the file name as note title.

**Comment by treeent** [comment]
Thanks, Selina!
